### ISSUE TITLE
Hay un error al ejecutar los datos semilla en heroku

### ISSUE THREAD

**Issue by jenlostar** [jenlostar/backend#1]
```
Running `rake db:seed` attached to terminal... up, run.2177
rake aborted!
LoadError: cannot load such file -- factory_girl
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `block in require'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:247:in `require'
/app/db/seeds.rb:9:in `<top (required)>'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `block in load'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:232:in `load_dependency'
/app/vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.5/lib/active_support/dependencies.rb:241:in `load'
/app/vendor/bundle/ruby/2.1.0/gems/railties-4.1.5/lib/rails/engine.rb:543:in `load_seed'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/tasks/database_tasks.rb:184:in `load_seed'
/app/vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.5/lib/active_record/railties/databases.rake:173:in `block (2 levels)
```

**Comment by jenlostar** [comment]
Resuelto con https://github.com/jenlostar/backend/commit/aa06a230769325d2ed7d7b7ae04c095175aae7e4
